### ISSUE TITLE
Some examples are missing a thumbnail

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat-space#102]
Hi Sean, after your awesome fix here: #77, and your modifications here #101, could you also add thumbnails for the few remaining examples that don't have one yet:
https://docs.tudat.space/en/latest/_src_getting_started/examples.html

**Comment by sbcowan** [comment]
This should be resolved with [this commit](https://github.com/tudat-team/tudat-space/commit/a558a8ebe6eb4b91dc0ae4fec533a91d3e6412b5).
