### ISSUE TITLE
broken link to example application

### ISSUE THREAD

**Issue by transferorbit** [tudat-team/tudat-space#104]
The link to a Cassini example application on [this documentation page](https://github.com/tudat-team/tudat-space/blob/505691fcc1953313d3bf62a80908dd3634883777/docs/source/_src_user_guide/astrodynamics/trajectory_design.rst) is broken (404 error). The link in [line 73](https://github.com/tudat-team/tudat-space/blame/505691fcc1953313d3bf62a80908dd3634883777/docs/source/_src_user_guide/astrodynamics/trajectory_design.rst#L73)  is in the following text:

`The associated code snippets are taken from an` [example application](https://docs.tudat.space/en/stable/_src_user_guide/astrodynamics/thisexample)`, for an unpowered leg Cassini (EVVEJS) transfer trajectory.`

**Comment by DominicDirkx** [comment]
Sounds like it fits well with what @sbcowan is already working on :)

**Comment by sbcowan** [comment]
This should be resolved with [this commit](https://github.com/tudat-team/tudat-space/commit/97b07b90a88178eb3abe2d97f7aa69999c49e72d).
