### ISSUE TITLE
Automatically sync .ipynb files between tudat-space and tudatpy-examples

### ISSUE THREAD

**Issue by sbcowan** [tudat-team/tudat-space#109]
Problem: It is tedious to update all the example applications with new code updates, and manually sync them between two repos.

Proposed solution: Using [Repo File Sync Action](https://github.com/marketplace/actions/repo-file-sync-action) from GitHub, you can sync files across repos. This should not require too much time to implement and would accelerate the process of updating example applications for Tudat.

This becomes even more efficient if you don't also have to convert .ipynb files to .py files.

**Comment by larshinueber** [comment]
Hi @sbcowan,
I've had a look at how to sync the notebooks between `tudatpy-examples` and `tudat-space`. The Repo File Sync Action looks like a good option, but there would still be two notebook files in different repositories.
Instead, I thought we could import `tudatpy-examples` directly as a submodule in `tudat-space`. This way, we avoid having to keep two files in sync and it is unambiguous where files should be maintained. The disadvantage with this approach is that there is some overhead with maintaining the submodule (the submodule commit needs to be kept up-to-date, although this might be automated with another Github action, see [this SO post](https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules)).

What do you think? I have created a draft PR with the proposed changes (#148), if you have any feedback or concerns with the approach, please let me know!
