### ISSUE TITLE
Link error in documentations

### ISSUE THREAD

**Issue by spacefan** [tudat-team/tudat-space#123]
The link [PyGMO tutorial](https://tudat-space.readthedocs.io/en/latest/_src_resources/pygmo_basics.html) in page [cassini1_mga_optimization](https://docs.tudat.space/en/latest/_src_getting_started/_src_examples/notebooks/pygmo/cassini1_mga_optimization.html) is invalid. Please consider repairing it!

**Comment by DominicDirkx** [comment]
Thanks for letting us know! We've corrected the links in our example repo:

https://github.com/tudat-team/tudatpy-examples

the website will be updated the next time the two are synced.
