### ISSUE TITLE
Link tudatpy functions to API reference in examples

### ISSUE THREAD

**Issue by larshinueber** [tudat-team/tudat-space#157]
As per the last development meeting, it would be nice to have links from tudatpy functions in the example applications to the API reference, making the API reference more accessible.
This is done in the matplotlib documentation, see e.g. https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html#sphx-glr-gallery-lines-bars-and-markers-bar-colors-py, and should be investigated how/if it can be done for tudat.

**Comment by larshinueber** [comment]
Looking further into this, matplotlib is using [sphinx-gallery](https://sphinx-gallery.github.io/stable/configuration.html#link-to-documentation) to automatically link from Python code to the API reference. sphinx-gallery seems to require the example files to be Python files with the comments being written in reST, see [here](https://sphinx-gallery.github.io/stable/syntax.html), which would mean having to convert all our examples to this specific format.

The other option I found is the [sphinx-codeautolink](https://sphinx-codeautolink.readthedocs.io/en/latest/) extension, which seems to work out of the box with our current setup, see the [feature/code-links](https://docs.tudat.space/en/feature-code-links) branch. The linking is not perfect, in [cell #4 of the Keplerian propagation example](https://docs.tudat.space/en/feature-code-links/_src_getting_started/_src_examples/tudatpy-examples/propagation/keplerian_satellite_orbit.html#Create-the-vehicle-settings) the `add_empty_settings` method is not linked, same as the `propagation_results` attribute in [cell #10](https://docs.tudat.space/en/feature-code-links/_src_getting_started/_src_examples/tudatpy-examples/propagation/keplerian_satellite_orbit.html#Propagate-the-orbit).
It seems that the extension does not recognize the return types of tudatpy functions, and then cannot infer subsequent method calls and attributes of a class instance.

In the [caveats of the extension](https://sphinx-codeautolink.readthedocs.io/en/latest/about.html#caveats) it is mentioned

> "Type hints of intersphinx-linked definitions are not necessarily available. Resolving names using type hints is only possible if the package is installed, but simple usage can be tracked via documentation entries alone."

so this might be an issue on our side and could possibly be resolved once we have stubs natively?

**Comment by DominicDirkx** [comment]
Also done!
