### ISSUE TITLE
Update website front page layout, and sub-pages

### ISSUE THREAD

**Issue by larshinueber** [tudat-team/tudat-space#158]
As per the last development meeting, currently the landing page does not have a clear "flow" and new users are presented with a (possibly overwhelming) number of options.

It was proposed to explore a different layout, where fewer options are presented initially, that the user can choose from. This should make it more clear what the audience for each section of the website is.
These sections could be the current sidebar headings (Getting Started, User Guide, Advanced Topics, About).

Inspiration could be drawn from the [NumPy documentation](https://numpy.org/doc/stable/).

**Comment by DominicDirkx** [comment]
Done!
