### ISSUE TITLE
Make list of available environment models more essential

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#20]
Take inspiration from #19.

**Comment by jo11he** [comment]
Comments on this matter:

o      using intersphinx for linking to api vs hyperlink
        + intersphinx is more elegant 
        -  intersphinx link not obvious
o     format of dependency (note environment --> needs new info environment)
o     (temporary) loss of info for c++ users

**Comment by jo11he** [comment]
missing in User guide
      ephemeris
                        direct spice
                        scaled (1,2,3) is documented as overload
      gravity
                        x
      atmosphere
                          constant wind
                          exponential predefined (overload of exponential?)
                          custom_four_dimensional_constant_temperature
                          scaled (1,2,3) is documented as overload
      shape
                        x
     rotation
                         constant
     atmosphere
                        custom
                        tabulated force only
                        scaled 1,2,3
     radiation pressure
                        x

**Comment by jo11he** [comment]
missing in tudatpy API

- ephemeris

                       
1.                           x


-    gravity

1.                         x

   

-    atmosphere

1.                           tabulated
    

-   shape

1.                         x

  

-    rotation

1.                          x

  

-    atmosphere

1.                         tabulated
2.                         local inclination methods

-    radiation pressure

1.                         colar sail

**Comment by jo11he** [comment]
Name mismatch:

Approximate Planet Ephemeris || approximate_jpl_model

**Comment by jo11he** [comment]
@DominicDirkx @FilippoOggionni 
I moved all info from User Guide to API reference. User guide still needs to be modified, I have a few ideas, which I will put up for discussion in slack tomorrow.
Else, in order to complete this task, I need a bit of input from @DominicDirkx on some details, for which I already posted in private slack conversation.

**Comment by DominicDirkx** [comment]
Thanks! I see the tudatpy API website has already been update. I looks really nice! Concerning the points you list above on stuff missing in the user guide, I think this we can resolve during the upcoming update of the user guide. For the points missing in the API, what does:

`tabulated (does not seem to have FF in tudat source --> delete from tudat-space )
`
mean?

The tabulated aerodynamics should be in the API, the other ones should not (yet).

**Comment by jo11he** [comment]
The point about missing factory function  is referring to tabulated under atmosphere, not aerodynamic.

The TabulatedAtmosphereModel ([source](https://github.com/tudat-team/tudat/blob/fa30c49dca7ee27630717efb8546802589a4c8b7/include/tudat/simulation/environment_setup/createAtmosphereModel.h#L492)) does not seem to have a factory function interface and is therefore excluded from tudatpy and the API reference.
Ideally we would make a factory function interface with one of  its many constructors and include it in tudatpy as well as the API reference.

You are right, tabulated (under aerodynamic) should indeed be in the API reference, there was a name mismatch, which is why it did not show up on the website... that is fixed now :)

**Comment by jo11he** [comment]
Implemented all the discussed points, is now very essential! Also adopted a normal tree structure w/o abusing rst's  ::class labels for the captions.
Changes are pushed to Filippo's user-guide-restyling branch.

Commit: https://github.com/tudat-team/tudat-space/commit/c1a3cd8f9b6514f03b230c61f5763383afe22c5f

**Comment by DominicDirkx** [comment]
Awesome! You can go ahead and merge this into the master

**Comment by DominicDirkx** [comment]
Merged! It seems that we're now pretty much done with a big milestone inour documentation. Many thanks to all who worked in it :)

**Comment by DominicDirkx** [comment]
https://tudat-space.readthedocs.io/en/latest/_src_user_guide/environment_setup/create_models/available.html#scaled-ephemeris
https://tudat-space.readthedocs.io/en/latest/_src_user_guide/environment_setup/create_models/available.html#scaled-ephemeris

Nice touch :)

**Comment by FilippoOggionni** [comment]
@jo11he from the tasks we agreed on yesterday, I also noted to leave `.. todo::` items in the list of environment models wherever there was an entry in the API not yet documented in the user guide (or vice-versa). Can you confirm this was done?

**Comment by FilippoOggionni** [comment]
Also, I would propose to turn the subsections (e.g., direct spice ephemeris, interpolated spice ephemeris, etc...) into simple, bold lines, because it looks a bit funny with only one line for each subsection. Also, it would make the page more compact and it would shorten the table of contents at the beginning of the page. On the other hand, specific types of environment models will not be "linkable" anymore. What do you guys think? @DominicDirkx @jo11he

**Comment by DominicDirkx** [comment]
I like the idea, below a screenshot of what it would look like:

![image](https://user-images.githubusercontent.com/5039068/140507695-b7a9e039-9114-404d-9354-d287b142d183.png)

**Comment by FilippoOggionni** [comment]
Nice! I would only insert a line break between the bold title and the description

**Comment by DominicDirkx** [comment]
![image](https://user-images.githubusercontent.com/5039068/140508618-34aef332-4cda-4da6-b382-f1a1df7e7a76.png)
![image](https://user-images.githubusercontent.com/5039068/140508824-6e6c57c3-d75e-4046-807d-afef068aa07e.png)

My preference goes to the second one, to make it more clear which title belongs to what

**Comment by FilippoOggionni** [comment]
I agree with the second option as well 👍

**Comment by DominicDirkx** [comment]
Done and pushed
