### ISSUE TITLE
Restructure and revise "home" + "about" pages

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#21]
The pages to be revised are:

- [home](https://tudat-space.readthedocs.io/en/latest/index.html)
- [about](https://tudat-space.readthedocs.io/en/latest/_src_about/about.html)

**Comment by DominicDirkx** [comment]
This is, at least partly, done right?

**Comment by FilippoOggionni** [comment]
Well, the content was split into two pages and I believe @jo11he made slight modifications to the homepage, but there is more to be done.

In any case, I think it is not high-priority, especially not for Numerical Astrodynamics.

**Comment by DominicDirkx** [comment]
> In any case, I think it is not high-priority, especially not for Numerical Astrodynamics.

Agreed :)

**Comment by FilippoOggionni** [comment]
@jo11he what is the status on this? Are you still gonna do it?

**Comment by jo11he** [comment]
No, sorry. This could be a task for Jeremie to pick up. I assigned him here and will discuss the scope with him soon. Unless you want to own this project now @FilippoOggionni ?

**Comment by FilippoOggionni** [comment]
No, that's fine, you can leave it to him!

**Comment by FilippoOggionni** [comment]
Some ideas that came up during the meeting with @gaffarelj and @jo11he:

**Home page**
- it should be more attractive
- it should give the user with a comprehensive overview of tudat functionalities
- it should provide some use cases
- it should provide an overview of the tudat-space and its organization
- it should provide external links to other tudat resources (developer docs, API reference, etc...)

**About page**
- it should tell the story of how tudat was born and maintained
- it should tell what is tudat today and where it will go in the future (roadmap?)

**Comment by gaffarelj** [comment]
Another discussion point was to move the entire content of the current about page:
- The first part about the functionalities of Tudat(Py) can be moved to the home pages.
- The second part about the examples of research carried using Tudat(Py) can be moved to a new page in "about" called **Success stories** (or something similar).

Also, we could try to find fancy figures from the reports currently referenced in "About" to put in the home page (helping to make it much more attractive).

**Comment by gaffarelj** [comment]
From today's meeting, point raised by @jo11he:
- We can take inspiration from [numpy documentation](https://numpy.org/) to get a more visually pleasing landing page.
Point raised by @ggarrett13:
- Material design elements can be available using the [`sphinx-panels` plugin](https://sphinx-panels.readthedocs.io/en/latest/).

**Comment by gaffarelj** [comment]
Tagging you here @jgte since you seemed interested in this issue.

**Comment by gaffarelj** [comment]
I want to confirm with you @FilippoOggionni that you are taking care of the home page (intro, overview, functionalities [including nice figures and use cases], and main links)?

I will then take care of the about page, and the new case studies page (also under about). This is less critical than the landing page, and lower on my task list.

**Comment by FilippoOggionni** [comment]
@gaffarelj first I will include some interactive panels in the landing page with all the difference resources and reorganize existing. About the other items (intro, overview, functionalities [including nice figures and use cases]), this is lower priority and I will use the team's input to add features.

I will leave the "about" page to you, but we can use the same methodology (i.e., asking for inputs and suggestions).

I will also create two different issues and close this one.
