### ISSUE TITLE
Reorganize user guide

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#22]
Tasks (to be divided among @jo11he and @FilippoOggionni): 

- [x] Reorganize general and pygmo examples
- [ ] Proof-read, and modify (if you’re confident) or suggest modifications:

   - https://tudat-space.readthedocs.io/en/latest/_src_user_guide/environment_setup/use_of_reference_frames.html
   - https://tudat-space.readthedocs.io/en/latest/_src_user_guide/environment_setup/create_bodies/default_settings.html
   - https://tudat-space.readthedocs.io/en/latest/_src_user_guide/mathematics.html#interpolators

Reorganize tudat block diagram and user guide content in a more user-oriented way (not necessarily module-wise):
- [x] state propagation overview
- [x] environment section
- [x] propagation section
- [x] numerical integration section

**Comment by FilippoOggionni** [comment]
Update on this: see pull request #36.

**Comment by FilippoOggionni** [comment]
Issue reopened because some tasks are not completed.

**Comment by jo11he** [comment]
@FilippoOggionni I will unassign myself from this, shall I add Jeremie or no need to?

**Comment by FilippoOggionni** [comment]
No need to 👍 only the proofreading is needed

**Comment by DominicDirkx** [comment]
I've resolved the review in the pull request, and have pushed a few very minor modifications to the documentation. I'm closing this issue, great to see how this page has shaped up!
