### ISSUE TITLE
Solve TODOs in list of available accelerations

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#24]
There are a few (low-priority) TODO points in the list of available acceleration models on tudat-space ([link](https://tudat-space.readthedocs.io/en/latest/_src_user_guide/propagation_setup/acceleration_models/available.html)). These were relayed from #19.
 
In addition to those, there are a few accelerations present in the API but not in tudat-space:

- custom
- momentum_wheel_desaturation_acceleration
- dedicated thrust page

**Comment by DominicDirkx** [comment]
Points have been resolved in API and user guide

**Comment by FilippoOggionni** [comment]
New tasks (I assigned myself):
- [ ] change regular links to intersphinx links
- [ ] revise page structure as agreed upon 
- [ ] change "API" to "API documentation" (also elsewhere)

**Comment by FilippoOggionni** [comment]
Changes on the `user-guide-restyling` branch were merged onto `master` locally by @DominicDirkx. 

The `user-guide-restyling` branch will be deleted to avoid future merge conflicts.

**Comment by FilippoOggionni** [comment]
The `user-guide-restyling` branch was deleted as agreed on.
