### ISSUE TITLE
Merge conflict in state propagation

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat-space#25]
Hi guys, when merging the docs from this issue:

https://github.com/tudat-team/tudat-space/issues/20

A small merge conflict arose, which I resolved, but I'm not sure if all the changes have been processed properly. The problem is with the changes made here:

https://github.com/tudat-team/tudat-space/commit/3d679004e254d97584f9e98d21c56e9ed960f74e#diff-ab2d4a6604a3c0bfdc605a4007faeba6cbdfbb4fb82bc3732e343442856e01a3

Most of these blocks of text have been moved to dedicated pages, and restructured:

https://github.com/tudat-team/tudat-space/blob/master/docs/source/_src_user_guide/running_simulation/single_arc.rst
https://github.com/tudat-team/tudat-space/blob/master/docs/source/_src_user_guide/running_simulation/single_variational_arc.rst

Since you guys have checked the first of these two pages already, could you confirm that this one is up to date with the unmerged changes, and modify if needed? Same goes for the second page on variational equations. The unmerged changes were small improvements and clarifications, so the issue not urgent, but good to keep on our radar

**Comment by FilippoOggionni** [comment]
Note: intersphinx links to classes are working, but the same for class _attributes_ are not working. Any idea why? @DominicDirkx @ggarrett13 @jo11he

**Comment by DominicDirkx** [comment]
Can you show an example?

**Comment by FilippoOggionni** [comment]
I was reading [this](https://tudat-space.readthedocs.io/en/latest/_src_user_guide/running_simulation/single_arc.html) page, see for instance the (black, not red) `SingleArcSimulator` and  `state_history`

**Comment by FilippoOggionni** [comment]
I checked out the available cross-referencing keys for python (see [here](https://www.sphinx-doc.org/en/1.5.1/domains.html#cross-referencing-python-objects)) and I have tried with:

- `:func:`
- `:class:`
- `:meth:`

but neither of them works 👎

**Comment by DominicDirkx** [comment]
Querying the full list of labels on the tudatpy API:

python -msphinx.ext.intersphinx https://tudatpy.readthedocs.io/en/latest/objects.inv

shows these elemens as py:property. I don't see a reference to this type of item anywhere, is it something of our own invention (@ggarrett13 ?)

**Comment by FilippoOggionni** [comment]
Also `:property:` does not work (as expected). Could you post a link to the line
`python -msphinx.ext.intersphinx https://tudatpy.readthedocs.io/en/latest/objects.inv`?

**Comment by FilippoOggionni** [comment]
Perhaps we should open another issue...

Coming back to the original issue, I think @jo11he is the right person to answer your question, because I have never committed any changes to the two pages you linked. If that's okay, I will leave it to him 😄

**Comment by DominicDirkx** [comment]
> Perhaps we should open another issue
For the issue with linking py:property: please do.

The line:
`python -msphinx.ext.intersphinx https://tudatpy.readthedocs.io/en/latest/objects.inv`
is a terminal command: it provides the full list of available labels

**Comment by jo11he** [comment]
I don't really see the need to intersphinx link the properties/attributes  - they are usually mentioned in the context of the linked class that they belong to. I won't dig into this. Will resolve the merge conflict and then move on.

**Comment by DominicDirkx** [comment]
No problem, I've opened a separate, lower priority issue (#27). Once you have a look at the specific point this post started with, this issue can be closed.

**Comment by FilippoOggionni** [comment]
> The line:
> python -msphinx.ext.intersphinx https://tudatpy.readthedocs.io/en/latest/objects.inv
> is a terminal command: it provides the full list of available labels

Nice trick! 
Thanks for opening a separate issue.
