### ISSUE TITLE
Establish correct lingo for "API documentation"

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-space#28]
While internally we often refer to the API Documentation simply as "API", we should ensure that on tudat-space and all other non-private platforms we use correct terminology. 

Valid options:
- API Documentation (*)
- API Docs
- API Reference

(*) preferred

TODOs: 

- [x]  Reminder message to all contributors to tudat-space
- [x] Go over all pages referencing the API Documentation and ensure correct usage

**Comment by jo11he** [comment]
@FilippoOggionni I think concerning point 1 we only need to go over our list of models (I suggest each their own), @DominicDirkx are there any additional pages referring to the API Documentations that you are aware of? If yes, please mention and I will take care of it.

**Comment by DominicDirkx** [comment]
My vote goes to: API Documentation

There may be a link on the NA Brightspace page. The main point is updating this on tudat-space. A search all for the term 'API' should do it (?). I did a quick search and replace on a bunch of them (not yet all), and pushed to master. I was having a look, tested to see how easy it was, and decided I might as well push them.

**Comment by DominicDirkx** [comment]
As a last small point, I modified the remaining entries in tudat-space to sat API documentation (there were one or two where it was, and should be, just API).

**Comment by FilippoOggionni** [comment]
I think we all agree on API Documentation 👍 

I am already replacing it for the list of available acceleration models. @jo11he, if you take care to check the list of available environment models and @DominicDirkx already replaced the rest, I think we are good to go.

**Comment by DominicDirkx** [comment]
I think I already took care of all of tudat-space...

**Comment by FilippoOggionni** [comment]
Both tasks completed, notification was sent to tudat-space contributors via Slack.
