### ISSUE TITLE
Find solution for "stashed" content from tudat-space environment/acceleration model lists

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat-space#30]
I had to stash a few (groups of) entries from the tudat-space environment model list, such that the entries perfectly mirror the environment submodules on the API Documentation. 

- [x] Gravity Field Variation Models  (exposed, not documented),  [related issue ](https://github.com/tudat-team/tudat-multidoc/issues/9)
- [x] Inertia Tensors (not exposed, not documented)
- [ ] Tabulated atmosphere (not exposed, not documented), related issue  #29

**Comment by jo11he** [comment]
@FilippoOggionni if you stashed any entries/ info for your acceleration model list, please list in bullet points here :)

**Comment by FilippoOggionni** [comment]
Backup file is available [here](https://github.com/tudat-team/tudat-space/blob/8964c10c750bdd7c12e0c012bbda01de4b1c2154/docs/source/_src_user_guide/state_propagation/environment_setup/create_models/info_backup.rst)
