### ISSUE TITLE
Add troubleshooting section for recurring errors under "Getting Started"

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#38]
I think we could create a troubleshooting page on the tudat-space listing the most common errors encountered by (new) users. A lot of inspiration could be taken from the Brightspace Installation forum of Numerical Astrodynamics. From what we see there and from our own experience, lots of issues come up while:

- creating the environment
- updating tudatpy

Recurring issues include:

- the DLL kernel import error
- errors in import statements, probably indicating that the tudatpy version is outdated
- etc…

This section should be quite essential and should only cover very basic errors, of course. 

If you have any other recurring errors, please post it below!

**Comment by larshinueber** [comment]
Hi all,
The recurring issues have been added to the [FAQ page](https://docs.tudat.space/en/latest/_src_getting_started/faq.html) in https://github.com/tudat-team/tudat-space/commit/875d4577431ea569d64709ee15d25c29a57775c1.

I checked this year's NA and P&O forums and the FAQ would have covered all issues. For more visibility, I linked the FAQ page in the installation instructions and the quickstart guide [here](https://github.com/tudat-team/tudat-space/pull/142/commits/5a40733a890499d9a42101e3db34b3b498125596), hopefully that will make the FAQ more present for new users.

If there is anything else to add, feel free to comment :)
