### ISSUE TITLE
Revise landing page

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#56]
[continuing from #21]

First, I will include some interactive panels in the landing page with all the difference resources and reorganize existing. About the other items (intro, overview, functionalities [including nice figures and use cases]), this is lower priority and I will use the team's input to add features.

**Comment by FilippoOggionni** [comment]
@DominicDirkx @jo11he @gaffarelj I have changed the landing page as we discussed, including links to external resources in the form of panels. Of course it could be improved and made more attractive than this, but first I wanted to check if you had specific ideas for the first three points below.

From #21:

- [ ] it should be more attractive
- [ ] it should give the user with a comprehensive overview of tudat functionalities
- [ ] it should provide some use cases
- [ ] it should provide an overview of the tudat-space and its organization
- [ ] it should provide external links to other tudat resources (developer docs, API reference, etc...)

**Comment by gaffarelj** [comment]
I agree with your proposal. I think we could get a few illustrations from published research when we want to illustrate some important points on the main about page, and then put more examples with more fancy illustrations in the "Case studies".

**Comment by FilippoOggionni** [comment]
I agree with you @gaffarelj that figures should be included only for the case studies and not for the current "array" of capabilities.

For now I have something like this, see attachment. I am not sure if the description of tudat-space as a "community" already applies... We could also switch the order between paragraphs, if needed. What do you think?

<img width="1104" alt="Screen Shot 2022-01-22 at 13 58 32" src="https://user-images.githubusercontent.com/57680167/150639515-6d3b55c6-d79f-4fe8-9b8f-47d063d1e6f0.png">

<img width="1072" alt="Screen Shot 2022-01-22 at 13 58 43" src="https://user-images.githubusercontent.com/57680167/150639519-583b974b-c84c-43cc-bb63-5043cea25b6a.png">

**Comment by FilippoOggionni** [comment]
Regarding the capabilities / scenarios that Tudat can simulate, I will make a draft of the list below, please feel free to add to this @DominicDirkx. It is a high-level list of categories, so it will not be exhaustive:

- Artificial satellite orbits (translational and rotational motion)
- Dynamics of celestial bodies in multi-body systems
- Interplanetary trajectories with high and low thrust
- Reentry trajectories of manned and unmanned vehicles
- Rocket launch trajectories
- Ascent and descent trajectories of planetary landers
- Guidance and control for the above cases

**Comment by gaffarelj** [comment]
The design is definitely more inviting than the current one. Great job!

Two small remarks:
- Could you change the italic text in the first image (Getting started, User guide...) to links.
- I would use a sub-title for the useful links/resources instead of the blue note. That separates things more clearly in my opinion. But I would still keep the message of the note (as normal text) between the sub-title and the boxes.

I agree that dividing between what tudatpy can do and a showcase of functionalities would be good. But I would keep the showcase concise (a few things that impress instead of a long list that loses the reader's attention), and link to the future Case studies for more detailed examples.

About the list of capabilities: perhaps we should remove control, and only keep guidance? We want to help develop guidance but nothing else from GNC (👀 the latest point from the developer meeting of last week).

**Comment by FilippoOggionni** [comment]
Thanks for the quick feedback!

> Could you change the italic text in the first image (Getting started, User guide...) to links.

Unfortunately I cannot do this, as those sections are not actual pages in the tudat-space, but only sections of the index/TOC.

> I would use a sub-title for the useful links/resources instead of the blue note. That separates things more clearly in my opinion. But I would still keep the message of the note (as normal text) between the sub-title and the boxes.

# Sure!

Regarding the rest, I agree, but I will wait to have Dominic's view on this before making further changes.

Last point: do you agree that having the section with API and developer docs before the current showcase of functionalities or should I switch it?

**Comment by jo11he** [comment]
Hell yeah this is great!

**Comment by FilippoOggionni** [comment]
I pushed the current changes in 4ba3d8fc4a756feef9cb5e0603ac7315832f23e5. I will wait for feedback before proceeding further.

We can also add some colors to make it a bit less homogeneous (see the sphinx-panels' [guide](https://sphinx-panels.readthedocs.io/en/latest/#installation)). Since the landing page is very important, I am dedicating extra attention to aesthetics as well 😃

**Comment by DominicDirkx** [comment]
> Hell yeah this is great!

What he said :)

**Comment by FilippoOggionni** [comment]
Happy to hear! The changes are already online, if you want me to make further modifications please let me know. 

@DominicDirkx when you have time, could you give us your opinion about the following points?

> In addition, for now the array of "capabilities" includes both a showcase of functionalities of tudatpy (e.g., customize body models) and things you can do with it (e.g., simulate the orbit estimation process). We may want to consider a clear division between the two. This is also done in Numpy's home page [here](https://numpy.org): they first show a 3x2 array of panels illustrating the strong points of numpy; down in the page they show a few case studies. Is this something we want to imitate? Our case studies can be a mix of research actually published and other case studies not published but that we know they can be achieved with Tudatpy.

> Regarding the capabilities / scenarios that Tudat can simulate, I will make a draft of the list below, please feel free to add to this @DominicDirkx. It is a high-level list of categories, so it will not be exhaustive:
> 
> * Artificial satellite orbits (translational and rotational motion)
> * Dynamics of celestial bodies in multi-body systems
> * Interplanetary trajectories with high and low thrust
> * Reentry trajectories of manned and unmanned vehicles
> * Rocket launch trajectories
> * Ascent and descent trajectories of planetary landers
> * Guidance and control for the above cases

**Comment by DominicDirkx** [comment]
> In addition, for now the array of "capabilities" includes both a showcase of functionalities of tudatpy (e.g., customize body models) and things you can do with it (e.g., simulate the orbit estimation process). We may want to consider a clear division between the two. This is also done in Numpy's home page here: they first show a 3x2 array of panels illustrating the strong points of numpy; down in the page they show a few case studies. Is this something we want to imitate? Our case studies can be a mix of research actually published and other case studies not published but that we know they can be achieved with Tudatpy.

I think this is a good distinction to make. The Numpy landing page looks very slick, and 'borrowing' elements of their design sounds good. Making case studies a mix of past and future potential work is a good idea.

**Comment by DominicDirkx** [comment]
> - Artificial satellite orbits (translational and rotational motion)
> - Dynamics of celestial bodies in multi-body systems
> - Interplanetary trajectories with high and low thrust
> - Reentry trajectories of manned and unmanned vehicles
> - Ascent and descent trajectories of planetary landers
> - Guidance and control for the above cases

I'll move this discussion to Slack

**Comment by gaffarelj** [comment]
I think you can setup a link so that the browser downloads the target instead of loading it in a tab. I can take a look at it this afternoon if you think it would make sense (and I would include the guide directly on the website then).

**Comment by FilippoOggionni** [comment]
Great idea! I did not think about it, thanks for the suggestion.

As a quick fix (but I think we should not spend more time on it), I uploaded the manual in the tudat-space repository via 1de7bda294ed9193182625a936dea4f3bbc69cde (i.e., it is hosted on Github) and I have set up the button so that pressing it will trigger the download (via 169f9af2b730b72edc9e3d665bb13db4fdd3daa6).

**Comment by geoffreygarrett** [comment]
I believe this is an appropriate place to couple the [`tudat-team/.github/profile/README.md`](https://github.com/tudat-team/.github/tree/main/profile) item for review. 

@FilippoOggionni & @DominicDirkx

**Comment by FilippoOggionni** [comment]
@geoffreygarrett good point. I moved your comment to a new issue (tudat-team/project-management#27), so I will close this as it is done.
