### ISSUE TITLE
Set maximum width to website

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#58]
This was originally proposed by @ggarrett13 some time ago. It is a good idea to avoid that the content gets stretched over width on very wide screens.

I tried with some solutions from this [post](https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs), but it was not successfully (in particular, setting `html_theme_options = {'body_max_width': '70%'}` in the `conf.py` file).

Assigning also @gaffarelj because he knows much more than me about CSS 😎

**Comment by FilippoOggionni** [comment]
Fixed by 8e226b644148d324123332f2e9b0417e5b739630. 

Turns out another solution from the same post linked above worked. Thanks to @ggarrett13 for the suggestion!

**Comment by FilippoOggionni** [comment]
This is now online. @gaffarelj @DominicDirkx please let me know if you think we should make it wider than the current version (currently set to 1000px [here](https://github.com/tudat-team/tudat-space/blob/78c4ef1f3d3c29e7966b9342bcc495821dc7ca81/docs/source/_static/custom.css#L2)).

**Comment by gaffarelj** [comment]
Seems perfect to me!
The old tudat.tudelft.nl is restricted to 800px, which feels a little to cramped. I think 1000px hits the mark just right.
