### ISSUE TITLE
Update user guide for multiple gravity assist trajectory design with low-thrust + create new examples

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat-space#68]
The code for trajectory design using multiple gravity assists was refactored to allow the inclusion of low-thrust legs (relevant pull requests: [https://github.com/tudat-team/tudat/pull/93](url) and [https://github.com/tudat-team/tudatpy/pull/69](url)).

The user guide for the transfer trajectory design module should be updated to reflect the new leg types (hodographic shaping and spherical shaping). Additionally, it might be worth mentioning that it is possible to create transfers by mixing different types of legs; that was already possible before the refactor, but not mentioned in the user guide.

Also, it would be cool to create some new examples: (1) example with low-thrust legs, and/or (2) example with a mix of high- and low-thrust legs. 
The attached code includes examples of: (1) transfer with just spherical-shaping legs ( `mga_with_spherical_shaping` function ); (2) transfer with just hodographic-shaping legs ( `mga_with_hodographic_shaping` function); (3) transfer with high-thrust leg, low-thrust leg and another high-thrust leg ( `mga_with_mixed_legs` function). The spherical and hodographic shaping examples show different ways (that can be changed using the `creation_mode` variable) to create the transfer leg and node settings: either by manually calling the factory function for each leg and node constituting the transfer, or by calling the factory function associated with the transfer trajectory for a specific leg type. Note that the values used for setting up these transfers are not necessarily realistic.
The other two functions included in the file ( `mga_without_dsm` and `mga_with_dsm`) are the examples with high-thrust legs already present on the tudat website.

[mga_dsm_analysis.py.zip](https://github.com/tudat-team/tudat-space/files/8819042/mga_dsm_analysis.py.zip)
Edit: updated example

**Comment by MiguelAvillez** [comment]
Tasks:
- [ ] Rewrite user guide
- [ ] High thrust example
- [ ] Low thrust example
- [ ] Hybrid thrust example
- [ ] Optimization example

Branches:
https://github.com/MiguelAvillez/tudat-space/tree/feature/mga_docs_ht_lt

**Comment by MiguelAvillez** [comment]
@DominicDirkx, the updated user guide for the MGA is available at https://github.com/MiguelAvillez/tudat-space/blob/feature/mga_docs_ht_lt/docs/source/_src_user_guide/astrodynamics/trajectory_design.rst
Feel free to have a look :)

**Comment by DominicDirkx** [comment]
@MiguelAvillez, all these changes have been made and merged right?

**Comment by MiguelAvillez** [comment]
Yep:
- https://github.com/tudat-team/tudat-space/pull/81
- https://github.com/tudat-team/tudatpy-examples/pull/12

Closing issue.
