### ISSUE TITLE
Documentation build error: Extension error - No module named 'sphinxcontrib.contentui'

### ISSUE THREAD

**Issue by transferorbit** [tudat-team/tudat-space#69]
The documentation is not building for me on my machine anymore.
When executing the command: `sphinx-build -b html docs/source docs/build`, I get the following error:

```
Running Sphinx v4.5.0

Extension error:
Could not import extension sphinxcontrib.contentui (exception: No module named 'sphinxcontrib.contentui')
```

I believe I am on the latest build; my last git log entry is:
```
commit 5e1008ba6077c1d2316c9fbb3b1d7ccf35c97ec0
Author: gaffarelj <jeremie@gaffarel.pro>
Date:   Sat Apr 9 16:59:36 2022 +0200

    Bump version: 0.3.1.dev0 → 0.3.1
```

Lists of the packages in my conda environments for [tudat-docs](https://github.com/tudat-team/tudat-space/files/8800647/tudat_docs_env_packaage_list.txt) and [tudat-space](https://github.com/tudat-team/tudat-space/files/8800650/tudat_space_env_packaage_list.txt).

**Comment by DominicDirkx** [comment]
Looks like a missing package, try:

pip install sphinxcontrib-contentui

Perhaps this is a new dependency, @gaffarelj  or @FilippoOggionni , do you have an idea?

**Comment by gaffarelj** [comment]
The issue is probably that the environment that is being updated is the one in [docs/environment.yaml](https://github.com/tudat-team/tudat-space/blob/master/docs/environment.yaml), while the one that most use is probably the one in root [environment.yaml](https://github.com/tudat-team/tudat-space/blob/master/environment.yaml). @FilippoOggionni @geoffreygarrett is there any reason for this duplication? If not I will keep the one in root only (with the latest dependencies).

**Comment by transferorbit** [comment]
I can confirm that the original yaml file I used (env yaml downloaded and installed fresh on 16 May 2022) is identical to the ‘root’ environment.yaml file @gaffarelj links to above (and thus not the above linked docs one). My file, and the ‘root’ one above, is _also_ identical to the yaml file on our current [sphinx developer documentation guide](https://tudat-developer.readthedocs.io/en/latest/primer/docs/sphinx.html#compile-documentation-with-sphinx). Of course, my environment may have been altered in the meantime if some packages were changed due to a `conda install ...` or `conda update ...`. (For what it’s worth: yes, I checked the relevant envs with `conda env list`.)

Nevertheless, I will reinstall the `tudat-docs` environment with the docs yaml file and report back.

**Comment by transferorbit** [comment]
I can now confirm that using the ‘root’ [environment](https://github.com/tudat-team/tudat-space/blob/master/environment.yaml) file works if I also add the (now, apparently) missing package using `conda install sphinxcontrib-contentui`. NB: no `pip` required.
In other words, the `sphinx-build ...` succeeds locally (with ≈220 warnings).

The question thus now remains:
- What is the status of this [docs/environment](https://github.com/tudat-team/tudat-space/blob/master/docs/environment.yaml) file?
- Are the additional packages in that environment file superfluous?

**Comment by DominicDirkx** [comment]
As a summary, if we add sphinxcontrib-contentui to the yaml file, and remove one of them, this is resolved?

**Comment by DominicDirkx** [comment]
Finally corrected in latest push to develop :)
