### ISSUE TITLE
Missing text for example applications

### ISSUE THREAD

**Issue by transferorbit** [tudat-team/tudat-space#77]
In the documentation [on this docs.tudat.space page](https://docs.tudat.space/en/stable/_src_getting_started/examples.html), the example applications are devoid of any text; they’re currently showing only small images of plots (see image below).
Some minimum level of text should be shown, such as a title and perhaps keywords.
<img width="1067" alt="Screenshot 2022-10-11 at 08 03 20" src="https://user-images.githubusercontent.com/19568006/195009445-1d4e2b5a-df77-48e6-a30f-862b5bac5d52.png">

**Comment by DominicDirkx** [comment]
Thanks! This used to look different in the older version, I'll try to find out what we messed up

**Comment by DominicDirkx** [comment]
On my old system, this error does not show up (and everything renders properly). On my new system, the layout is messed up, as it is in the online build. I'll attach the conda environment contents here for future diagnostics
[old_conda.txt](https://github.com/tudat-team/tudat-space/files/10246215/old_conda.txt)

**Comment by DominicDirkx** [comment]
[new_conda.txt](https://github.com/tudat-team/tudat-space/files/10246231/new_conda.txt)

**Comment by DominicDirkx** [comment]
old_conda.txt **Build shows up properly**
new_conda.txt **Build is messed up (as online)**

**Comment by sbcowan** [comment]
The problem lies indeed with the sphinx-gallery package. In builds with sphinx-gallery=0.11.1 the gallery is formatted incorrectly, in sphinx-gallery=0.10.1 the gallery is correct. I presume this has to be changed in the conda packages for tudat-docs. Should I bissect where the cut-off point is or do we just stick with 0.10.1 for now?

**Comment by DominicDirkx** [comment]
Thanks for pinpointing this! I'll fix the version to 0.10.1 on readthedocs

**Comment by DominicDirkx** [comment]
So, good news and bad news :) I made the modifications to the environment.yaml file:

**Comment by DominicDirkx** [comment]
Scratch the above, my browser was showing the cached version. Loading it anew shows it as it should! Nice!
