### ISSUE TITLE
'Importing' Jupyter notebooks

### ISSUE THREAD

**Issue by sbcowan** [tudat-team/tudat-space#87]
For the [asteroid orbit optimization](https://docs.tudat.space/en/latest/_src_getting_started/_src_examples/notebooks/pygmo/asteroid_orbit_optimization.html) example, it is best to split it into multiple parts, due to its extensive length. However, it is also desirable for these notebooks to remain runnable by themselves. It would therefore be ideal to be able to 'import' jupyter notebooks, such that there are three shorter examples that are all independently runnable. This may be useful for other examples in the future as well.

**Comment by kgzenk** [comment]
https://ipynb.readthedocs.io/en/stable/ is what I have used. So, after installing ipynb, either

from ipynb.fs.full.<notebook_name> import <function_name>
or
from ipynb.fs.defs.<notebook_name> import <function_name> (preferred, I guess)

should do the trick...

**Comment by sbcowan** [comment]
This will be resolved with #113.
